Minor improvements
ehlesp/smallab-k8s-pve-guide pull request #9
Opened 2023-06-26 09:55 UTC by kriegalex

1. Help user notice that tls-san is the same value as entry in /etc/hosts (not sure if it could break k3s service).
2. Help user notice that the overcommit flag is commented because it expects it from another sysctl config.

2023-07-16 10:07 UTC, ehlesp requested changes
Sorry I didn't review your changes sooner.

2023-07-16 10:07 UTC, ehlesp commented on G911 - Appendix 11 ~ Alternative Nextcloud web server setups.md
> +    > - It is always a good idea to compare your nginx.conf against the one found [in the Nextcloud documentation](https://docs.nextcloud.com/server/stable/admin_manual/installation/nginx.html), for
Remove the "-", there's no need for it here in this case (check my review about your second bulleted line). Also, write \`nginx.conf\` (notice the punctuation marks), to give the filename the shell highlighting.

2023-07-16 10:07 UTC, ehlesp commented on G911 - Appendix 11 ~ Alternative Nextcloud web server setups.md
> +    > - If you get a message like `Error occurred while checking server setup` in the overview screen of the administration section of Nextcloud, carefully look into the logs of your nextcloud pod ([
To separate this sentence from the previous one, you just have to add a blank `>` line, as follows:

~~~markdown
>
> If you get a message like...
~~~

This saves you from using bullet points when you want to separate lines in a quote. So please remove the bullet point here too.

2023-10-24 14:08 UTC, kriegalex commented
I'll review and update this at some point, no worries. Sorry for the many English syntax errors in the doc, it is not my main language. Thanks for the tips.

Context: I've taken a break from k3s since I'm still waiting to build my "real" homelab server that will host k3s. I quickly followed your guide on a very basic system to validate the whole concept.

2023-10-25 18:16 UTC, ehlesp commented
> I'll review and update this at some point, no worries. Sorry for the many English syntax errors in the doc, it is not my main language. Thanks for the tips.
> 
> Context: I've taken a break from k3s since I'm still waiting to build my "real" homelab server that will host k3s. I quickly followed your guide on a very basic system to validate the whole concept.

Understood @kriegalex . Don't worry about your english, many in IT are not english speakers (disclaimer, I'm spanish so we are in the same boat). I'll just correct the texts where necessary, but be careful that what you put has been tested and works. Like you, I don't have a K3s system with me right now, although maybe when I have the time I'll create a new one, although with a different setup.

I'll assign you to this pull request since I think it'll be more convenient for future related notifications, hope you don't mind. Don't worry, I won't bother you at all about this. We're not in a rush at all.

Thanks for your contribution!

2024-08-05 09:00 UTC, kriegalex commented
I'm closing this pull request as I ended up not following this guide for my final cluster, so I didn't work on it that much. I went with bare metal, K8S and helm instead of Proxmox, K3S and Kustomize.

The only real valuable things from this pull request are:

- nginx-config vs fpm-config in G911
- server vs apache in G033

Thank you for this very good guide, the details help understand things as a beginner.

2024-08-05 09:00 UTC, closed without merging